routes/web.php
<?php
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ZakatController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  
Auth::routes();
  
Route::group(['middleware' => ['auth']], function() {
    Route::match(['GET','POST'],'logout', [LoginController::class, 'logout'])->name('logout');
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('/force-logout/{id}', [UserController::class, 'force_logout'])->name('forceLogout');
    Route::post('/user-change-status/{id}', [UserController::class, 'change_status'])->name('changeStatus');
    Route::get('/zakat-fitrah/{id}/per-ronda', [ZakatController::class, 'index_peronda'])->name('zakat-fitrah.peronda');
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('zakat-fitrah', ZakatController::class);
});

app/Models/Zakat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Zakat extends Model
{
    use HasFactory;

    protected $table = 'zakat';
    protected $fillable = [        
        'nama',
        'tanggal',        
        'user_id',        
        'jenis',        
        'jumlah_beras',        
        'jumlah_uang',        
        'sisa_uang',        
        'sudah_beli',        
    ];  

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
}

app/Http/Controllers/Admin/ZakatController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Zakat;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\File; 
use DB;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class ZakatController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:zakat-list|zakat-create|zakat-edit|zakat-delete', ['only' => ['index','show']]);
         $this->middleware('permission:zakat-create', ['only' => ['create','store']]);
         $this->middleware('permission:zakat-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:zakat-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $roleName = $user->roles->pluck('name')[0];                
        if ($roleName == 'Admin' || $roleName == 'Takmir Masjid') {
            $data = User::role('Amil Zakat')->get();
            foreach ($data as $key => $value) {
                $uang = Zakat::where('user_id',$value->id)->where('jenis','uang')->count();
                $beras = Zakat::where('user_id',$value->id)->where('jenis','beras')->count();
                $value->jumlah_muzaki = $uang + $beras;
                $value->jumlah_uang = $uang;
                $value->jumlah_beras = $beras;
            }
            $this->data['data'] = $data;

            return view('zakat.index_admin',$this->data);
        } else {
            $data = Zakat::where('user_id',$user->id)->orderBy('tanggal','DESC')->get();
            $this->data['data'] = $data;        
            $this->data['amil'] = Auth::user();

            return view('zakat.index',$this->data);
        }                
    }

    public function index_peronda($id)
    {
        $user = User::findOrFail($id);
        $this->data['amil'] = $user;
        $this->data['data'] = Zakat::where('user_id',$user->id)->orderBy('tanggal','DESC')->get();

        return view('zakat.peronda',$this->data);
    }

    public function create()
    {                    
        $this->data['now'] = Carbon::now()->format('m/d/Y');

        return view('zakat.create', $this->data);
    }

    public function store(Request $request)
    {        
        $validator = Validator::make($request->all(), [
            'tanggal' => 'required',
            'nama' => 'required',
            'jenis' => 'required|IN:beras,uang',
            'jumlah_beras' => 'nullable',            
            'jumlah_uang' => 'nullable',            
            'sisa_uang' => 'nullable',            
            'sudah_beli' => 'nullable',            
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }      

        $zakat = new Zakat();
        $zakat->user_id = Auth::id();
        $zakat->nama = $request->nama;
        $split = explode('/',$request->tanggal);
        $zakat->tanggal = $split[2].'-'.$split[0].'-'.$split[1];
        $zakat->jenis = $request->jenis;
        if ($request->jenis == 'beras') {
            $zakat->jumlah_beras = $request->jumlah_beras;
            $zakat->jumlah_uang = null;
            $zakat->sisa_uang = null;
            $zakat->sudah_beli = 0;
        }else {
            $zakat->jumlah_beras = null;
            $zakat->jumlah_uang = '36000';
            if ($request->has('sudah_beli')) {
                $zakat->sudah_beli = 1;
            }else {
                $zakat->sudah_beli = 0;
            }    
            $sisa = str_replace(".","",$request->sisa_uang);
            $sisa = str_replace(",",".",$sisa);
            $zakat->sisa_uang = $sisa;            
        }
        $simpanZakat = $zakat->save();        
        if ($simpanZakat) {            
            toast('Zakat atas nama '.$request->nama.' berhasil disimpan!','success');

            return redirect()->route('zakat-fitrah.create');
        }else {
            toast('Zakat atas nama '.$request->nama.' gagal disimpan!','danger');            

            return back();
        }        
    }   

    public function edit($id)
    {
        $data = Zakat::findOrFail($id);
        $split = explode('-',$data->tanggal);
        $data->tanggal = $split[1].'/'.$split[2].'/'.$split[0];
        $this->data['data'] = $data;

        return view('zakat.edit', $this->data);
    }

    public function update(Request $request,$id)
    {
        $validator = Validator::make($request->all(), [
            'tanggal' => 'required',
            'nama' => 'required',
            'jenis' => 'required|IN:beras,uang',
            'jumlah_beras' => 'nullable',            
            'jumlah_uang' => 'nullable',            
            'sisa_uang' => 'nullable',            
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }      

        $zakat = Zakat::where('id',$id)->first();
        $zakat->user_id = Auth::id();
        $zakat->nama = $request->nama;
        $split = explode('/',$request->tanggal);
        $zakat->tanggal = $split[2].'-'.$split[0].'-'.$split[1];
        $zakat->jenis = $request->jenis;
        if ($request->jenis == 'beras') {
            $zakat->jumlah_beras = $request->jumlah_beras;
            $zakat->jumlah_uang = null;
            $zakat->sisa_uang = null;
            $zakat->sudah_beli = 0;
        }else {
            if ($request->has('sudah_beli')) {
                $zakat->sudah_beli = 1;
            }else {
                $zakat->sudah_beli = 0;
            }    
            $zakat->jumlah_beras = null;
            $zakat->jumlah_uang = '36000';
            $sisa = str_replace(".","",$request->sisa_uang);
            $sisa = str_replace(",",".",$sisa);
            $zakat->sisa_uang = $sisa;            
        }
        $simpanZakat = $zakat->save();        
        if ($simpanZakat) {            
            toast('Zakat atas nama '.$request->nama.' berhasil diupdate!','success');

            return redirect()->route('zakat-fitrah.index');
        }else {
            toast('Zakat atas nama '.$request->nama.' gagal diupdate!','danger');            

            return back();
        }  
    }

    public function show($id)
    {        
        $this->data['data'] = AjaibNews::findOrFail($id);
        
        return view('ajaib_news.show',$this->data);
    }

    public function destroy($id)
    {
        $zakat = Zakat::where('id',$id)->first();        
        if (!$zakat) {
            toast('Data tidak ditemukan!','danger');

            return redirect()->route('zakat-fitrah.index');
        }        
        $nama = $zakat->nama;
        $delete = $zakat->delete();
        if ($delete) {            
            toast('Data zakat atas nama '.$nama.' berhasil dihapus!','success');
        } else {
            toast('Data zakat atas nama '.$nama.' gagal dihapus!','danger');
        }        
        return redirect()->route('zakat-fitrah.index');
    }

}

resources/views/zakat/create.blade.php
@extends('layouts.app')

@section('title')
    <title>Halaman Zakat</title>
@endsection
@section('cssAdded')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" />    
    <style>
        .required:after {
            content:" *";
            color: red;
        }        
        .required2:before {
            content:" *";
            color: red;
        }        
    </style>
@endsection
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Manajemen Zakat Fitrah</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('zakat-fitrah.index') }}">Zakat Fitrah</a></li>
                    <li class="breadcrumb-item active">Tambah Zakat Fitrah</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('zakat-fitrah.store') }}">
                @csrf                
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="required">Date</label>
                        <input type="text" class="form-control" name="tanggal" id="datepicker" value="{{ $now }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="required">Nama Muzaki</label>
                        <input type="text" class="form-control" id="nama" name="nama" value="" placeholder="masukkan nama muzaki" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="required">Pilih Jenis Zakat</label>
                        <select name="jenis" id="jenis" class="form-control" required>
                            <option value="">-- Pilih Jenis Zakat --</option>
                            <option value="beras">Beras</option>
                            <option value="uang">Uang</option>
                        </select>
                    </div>
                    <div id="berasArea" style="display: none;">
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="required">Jumlah (Kg)</label>
                            <input type="text" class="form-control" id="jumlah_beras" name="jumlah_beras" value="3">
                            <span class="required2">Gunakan tanda (.) untuk pemisah, misal 3.5kg cukup ditulis 3.5</span>
                        </div>
                    </div>
                    <div id="uangArea" style="display: none;">
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="required">Jumlah Uang (rupiah)</label>
                            <input type="text" class="form-control" name="jumlah_uang" id="jumlah_uang" value="{{ old('harga_avg') ? old('harga_avg') : "36.000" }}">
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-checkbox custom-control-inline">
                                <input type="checkbox" name="sudah_beli" class="custom-control-input parentPermission" data-kunci="1" id="sudah_beli" value="1" @if (old('sudah_beli') == '1')
                                    checked
                                @endif>
                                <label class="custom-control-label" for="sudah_beli" style="padding-top:3px;">Sudah Dibelikan Beras ?</label>
                            </div>
                        </div>     
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="required">Sisa (Shodaqoh)</label>
                            <input type="text" class="form-control" name="sisa_uang" id="sisa_uang" value="{{ old('harga_avg') ? old('harga_avg') : 0 }}" readonly>
                        </div>
                    </div>
                    <div style="text-align:right;">
                        <a href="{{ route('zakat-fitrah.index') }}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>                
            </form>
        </div>
    </div>
</section>
@include ('includes.script')   
    @section('jsAdded')    
        <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js" type="text/javascript"></script>
        <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css" />                
        <script>            
            $('#datepicker').datepicker({
                uiLibrary: 'bootstrap4'
            });

            $('#datepicker').datepicker({
                uiLibrary: 'bootstrap4'
            });

            $('#jumlah_beras').on('change, keyup', function() {
                var currentInput = $(this).val();
                var fixedInput = currentInput.replace(/[A-Za-z!,@#$%^&*()]/g, '');
                $(this).val(fixedInput);
            });

            jmlUang = null;
            uangInt = null;
            sisa = 0;
            $('#jumlah_uang').on('change, keyup', function() {
                jmlUang = $(this).val();
                jmlUang = jmlUang.replace(/[A-Za-z!,@#$%^&*()]/g, '');
                $(this).val(jmlUang);
                if (jmlUang == '') {
                    uangInt = 36000;                    
                    sisa = 0;
                    $("#sisa_uang").val(sisa.toLocaleString("id-ID"));
                    $("#jumlah_uang").val('');
                } else {                    
                    uangInt = jmlUang.replace('.', '')
                    uangInt = uangInt.replace(',', '.')                    
                    uangInt = parseInt(uangInt);
                    if (uangInt > 36000) {
                        sisa = uangInt - 36000;
                    } else if (uangInt <= 36000) {                        
                        sisa = 0;
                    }
                    $("#jumlah_uang").val(uangInt.toLocaleString("id-ID"));
                    $("#sisa_uang").val(sisa.toLocaleString("id-ID"));
                }                                                
            });
        
            let jenis = null;
            $(document).on('change','#jenis',function(){
                event.preventDefault();            
                jenis = $('#jenis option:selected').val();                
                if (jenis == 'beras') {
                    $("#berasArea").show();
                    $("#uangArea").hide();                    
                }else if(jenis == 'uang'){
                    $("#berasArea").hide();
                    $("#uangArea").show();
                }else {
                    $("#berasArea").hide();
                    $("#uangArea").hide();
                }
                $("#jumlah_beras").val(3);
                $("#jumlah_uang").val("36.000");
                $("#sisa_uang").val(0);
            });           

        </script>
    @endsection
@endsection

resources/views/zakat/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Halaman Zakat</title>
@endsection
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Manajemen Zakat <small><span class="badge badge-pill badge-info">{{ $amil->name }}</span></small></h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Manajemen Zakat {{ $amil->name }}</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">    
    @include ('includes.flash')
    <div class="card shadow mb-4">
        <div class="card-body">  
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <table id="data-admin" class="table table-bordered dataTable table-striped">
                        <thead>
                            <tr>
                                <th width="40">No</th>
                                <th>Tanggal</th>           
                                <th>Muzaki</th>           
                                <th>Beras</th>                    
                                <th>Uang</th>                    
                                <th>Sudah Dibelikan</th>                    
                                <th>Shodaqoh</th>                    
                                <th width="120">ACTION</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $key => $an)
                                <tr>
                                    <td class="text-center">{{$loop->iteration}}</td>
                                    <td>{{ \Carbon\Carbon::parse($an->tanggal)->format("l, d F Y") }}</td>                                                        
                                    <td>
                                        {{ $an->nama }}
                                    </td>                                                            
                                    <td>
                                        @if ($an->jumlah_beras != null)
                                            {{ $an->jumlah_beras }} Kg
                                        @else
                                            -
                                        @endif
                                    </td>                        
                                    <td>
                                        @if ($an->jumlah_uang != null)
                                            @currency($an->jumlah_uang)
                                        @else
                                            -
                                        @endif
                                    </td>  
                                    <td>
                                        @if ($an->jenis == 'beras')
                                            -
                                        @else
                                            @if ($an->sudah_beli == '1')
                                                <i class="fa fa-check" style="color:cornflowerblue;"></i> Sudah
                                            @else
                                                <i class="fa fa-times" style="color:firebrick;"></i> Belum
                                            @endif
                                        @endif    
                                    </td>                                                          
                                    <td>
                                        @if ($an->sisa_uang != null)
                                            @currency($an->sisa_uang)
                                        @else
                                            -
                                        @endif
                                    </td>                                                            
                                    <td class="text-center">                                        
                                        @can('zakat-edit')
                                            <a href="{{ route('zakat-fitrah.edit',$an->id) }}">
                                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-pencil"></i></button>
                                            </a>
                                        @endcan
                                        @can('zakat-delete')
                                            <button type="button" class="btn btn-danger btnDelete" data-nama="{{ $an->nama }}" data-id="{{ $an->id }}" data-toggle="tooltip" data-placement="top" title="Delete">
                                                <i class="fa fa-trash"></i>
                                            </button>                            
                                        @endcan
                                    </td>
                                </tr>                        
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
    @include('includes.modals_delete')
    @include ('includes.script')
    @can('zakat-create')
        <script type="text/javascript">
            $(document).ready(function(){
                $("#data-admin_length").append('<a  href="{{ route('zakat-fitrah.create') }}"> <button type="button" class="btn btn-outline-primary ml-3"><i class="fa fa-plus"></i> Zakat</button></a>');
            });
        </script>
    @endcan
    @section('jsAdded')
        <script>
            let id = null;
            let url = null;
            let msg = null;
            let name = null;

            $(document).on('click','.btnDelete',function(){
                id = $(this).data('id');
                name = $(this).data('nama');
                url = "{{ route('zakat-fitrah.destroy', '') }}"+"/"+id;
                msg = "Apakah kamu yakin ingin menghapus zakat atas nama ("+name+") ?";
                $('#formDelete').attr('action', url);            
                $('#modalContent').empty();
                $('#modalContent').append(msg);
                $('#modalDelete').show();
            });

            $(document).on('click','.btnCancel',function(){            
                $('#modalDelete').hide();
            });
        </script>
    @endsection
@endsection

resources/views/zakat/index_admin.blade.php
@extends('layouts.app')

@section('title')
    <title>Halaman Zakat</title>
@endsection
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Manajemen Zakat</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Zakat Fitrah</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">    
    @include ('includes.flash')
    <div class="card shadow mb-4">
        <div class="card-body">  
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <table id="data-admin" class="table table-bordered dataTable table-striped">
                        <thead>
                            <tr>
                                <th width="40">No</th>
                                <th>Kelompok Ronda</th>           
                                <th>Jumlah Muzaki</th>           
                                <th>Beras</th>                    
                                <th>Uang</th>                    
                                <th width="120">ACTION</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $key => $an)
                                <tr>
                                    <td class="text-center">{{$loop->iteration}}</td>
                                    <td>{{ $an->name }}</td>                                                        
                                    <td>
                                        {{ $an->jumlah_muzaki }} orang
                                    </td>                                                            
                                    <td>
                                        {{ $an->jumlah_beras }} orang
                                    </td>                                                            
                                    <td>
                                        {{ $an->jumlah_uang }} orang
                                    </td>                                                                                                                                                          
                                    <td class="text-center">
                                        @can('zakat-list')
                                            <a href="{{ route('zakat-fitrah.peronda',$an->id) }}">
                                                <button class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Detail"><i class="fa fa-eye"></i> Detail</button>
                                            </a>
                                        @endcan                                        
                                    </td>
                                </tr>                        
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
    @include('includes.modals_delete')
    @include ('includes.script')
    @can('zakat-create')
    @endcan
    @section('jsAdded')
        <script>
            let id = null;
            let url = null;
            let msg = null;
            let name = null;

            $(document).on('click','.btnDelete',function(){
                id = $(this).data('id');
                name = $(this).data('nama');
                url = "{{ route('zakat-fitrah.destroy', '') }}"+"/"+id;
                msg = "Apakah kamu yakin ingin menghapus zakat atas nama ("+name+") ?";
                $('#formDelete').attr('action', url);            
                $('#modalContent').empty();
                $('#modalContent').append(msg);
                $('#modalDelete').show();
            });

            $(document).on('click','.btnCancel',function(){            
                $('#modalDelete').hide();
            });
        </script>
    @endsection
@endsection