routes/web.php
<?php
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ZakatController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  
Auth::routes();
  
Route::group(['middleware' => ['auth']], function() {
    Route::match(['GET','POST'],'logout', [LoginController::class, 'logout'])->name('logout');
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('/force-logout/{id}', [UserController::class, 'force_logout'])->name('forceLogout');
    Route::post('/user-change-status/{id}', [UserController::class, 'change_status'])->name('changeStatus');
    Route::get('/zakat-fitrah/{id}/per-ronda', [ZakatController::class, 'index_peronda'])->name('zakat-fitrah.peronda');
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('zakat-fitrah', ZakatController::class);
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

class RoleController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
         $this->middleware('permission:role-create', ['only' => ['create','store']]);
         $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        $myRole = $user->roles()->pluck('id')->first();
        $this->data['roles'] = Role::where('id','!=',$myRole)->orderBy('id','DESC')->get();

        return view('roles.index',$this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parent = [
                        'role','user','zakat',
                    ];
        $permissionData = [];
        foreach ($parent as $key => $value) {
            $list = $value.'-list';
            $create = $value.'-create';
            $edit = $value.'-edit';
            $delete = $value.'-delete';
            $data = Permission::whereIn('name',[$list,$create,$edit,$delete])->orderBy('created_at','ASC')->get();
            $permissionData[$value] = $data;
        }        
        $this->data['permissions'] = $permissionData;
        
        return view('roles.create',$this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:roles,name',
            'permissions' => 'required',
        ]);
        
        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }
        
        $role = Role::create(['name' => $request->input('name')]);
        if ($role) {
            $role->syncPermissions($request->input('permissions'));            
            toast('Role created successfully!','success');
        }else {            
            toast('Role failed to created!','danger');
        }        
    
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        if (!$role) {
            toast('Role failed to created!','danger');

            return redirect()->route('roles.index');
        }
        $this->data['role'] = $role;
        $this->data['rolePermissions'] = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
                                                    ->where("role_has_permissions.role_id",$id)
                                                    ->get();
    
        return view('roles.show',$this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        if (!$role) {
            toast('Role failed to created!','danger');

            return redirect()->route('roles.index');
        }
        $parent = [
                    'role','user','zakat',
                ];
        $permissionData = [];
        foreach ($parent as $key => $value) {
        $list = $value.'-list';
        $create = $value.'-create';
        $edit = $value.'-edit';
        $delete = $value.'-delete';
        $data = Permission::whereIn('name',[$list,$create,$edit,$delete])->orderBy('created_at','ASC')->get();
        $permissionData[$value] = $data;
        }        
        $this->data['permissions'] = $permissionData;
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
        
        $this->data['role'] = $role;        
        $this->data['rolePermissions'] = $rolePermissions;

        return view('roles.edit',$this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:roles,name,'.$id,
            'permissions' => 'required',
        ]);
        
        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }
    
        $role = Role::find($id);
        if (!$role) {
            toast('Role failed to created!','danger');

            return redirect()->route('roles.index');
        }
        $role->name = $request->input('name');
        $simpan = $role->save();
        if ($simpan) {
            $role->syncPermissions($request->input('permissions'));
            toast('Role updated successfully!','success');

            return redirect()->route('roles.index');
        } else {
            toast('Role failed to update!','danger');

            return redirect()->route('roles.edit',$id);
        }                    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = DB::table("roles")->where('id',$id)->delete();

        if ($delete) {
            toast('Role deleted successfully!','success');
        } else {
            toast('Role failed to delete!','danger');
        }        

        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')
@section('title')
    <title>Add Role</title>
@endsection
@section('cssAdded')
    <style>
        .table-borderless > tbody > tr > td,
        .table-borderless > tbody > tr > th,
        .table-borderless > tfoot > tr > td,
        .table-borderless > tfoot > tr > th,
        .table-borderless > thead > tr > td,
        .table-borderless > thead > tr > th {
            border: none;
        }
    </style>
@endsection
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Roles Management</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                    <li class="breadcrumb-item active">Add Role</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('roles.store') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1"><b>Role Name</b></label>
                        <input type="text" class="form-control" id="name" name="name" id="exampleInputPassword1" placeholder="Role Name" required>
                    </div>
                    <br>
                    <h4>Permissions</h4>
                    <div class="custom-control custom-checkbox small">                        
                        <table class="table table-borderless">
                            @foreach ($permissions as $key => $permission)
                                <tr>
                                    <td>
                                        <input type="checkbox" class="custom-control-input parentPermission" data-kunci="{{ $key }}" id="{{ $key }}" value="{{ $key }}">
                                        <label class="custom-control-label" for="{{ $key }}" style="padding-top:3px;"><b>{{ ucwords($key) }} Module</b></label>
                                    </td>
                                    @foreach ($permission as $key2 => $item)
                                    <td>
                                        <input type="checkbox" name="permissions[]" class="custom-control-input" id="{{ $item->name }}" value="{{ $item->id }}">
                                        <label class="custom-control-label" for="{{ $item->name }}" style="padding-top:3px;">{{ ucwords(explode('-', $item->name)[1]) }}</label>
                                    </td>
                                    @endforeach
                                </tr>
                            @endforeach                            
                        </table>                                                                                                                        
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ route('roles.index') }}" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@section('jsAdded')
    <script>
        let kunci = null;
        let isChecked = null;
        let create = null;
        let list = null;
        let edit = null;
        let del = null;
        $(document).on('click','.parentPermission',function(){
            kunci = $(this).data('kunci');
            isChecked= $('#' + kunci).is(":checked");
            create = kunci+'-create';
            list = kunci+'-list';
            edit = kunci+'-edit';
            del = kunci+'-delete';
            if (isChecked == true) {
                $('#' + create).prop("checked", true );
                $('#' + list).prop("checked", true );
                $('#' + edit).prop("checked", true );
                $('#' + del).prop("checked", true );
            }else {
                $('#' + create).prop("checked", false );
                $('#' + list).prop("checked", false );
                $('#' + edit).prop("checked", false );
                $('#' + del).prop("checked", false );
            }
        });

    </script>
@endsection
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('title')
    <title>Edit Role</title>
@endsection
@section('cssAdded')
    <style>
        .table-borderless > tbody > tr > td,
        .table-borderless > tbody > tr > th,
        .table-borderless > tfoot > tr > td,
        .table-borderless > tfoot > tr > th,
        .table-borderless > thead > tr > td,
        .table-borderless > thead > tr > th {
            border: none;
        }
    </style>
@endsection
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Roles Management</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                    <li class="breadcrumb-item active">Edit Role</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('roles.update',$role->id) }}">
                @csrf
                @method('put')
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1"><b>Role Name</b></label>
                        <input type="text" class="form-control" id="name" name="name" id="exampleInputPassword1" value="{{ $role->name }}" required>
                    </div>
                    <br>
                    <h4>Permissions</h4>
                    <div class="custom-control custom-checkbox small">                        
                        <table class="table table-borderless">
                            @foreach ($permissions as $key => $permission)
                                @php
                                    $inc = 0;
                                    $cek = 0;
                                    foreach ($permission as $k => $value) {
                                        if (in_array($value->id,$rolePermissions)) {
                                            $inc++;
                                        }
                                    }
                                    if ($inc > 0) {
                                        $cek = 1;
                                    }
                                @endphp
                                <tr>
                                    <td>
                                        <input type="checkbox" class="custom-control-input parentPermission" data-kunci="{{ $key }}" id="{{ $key }}" value="{{ $key }}" @if ($cek == 1)
                                            checked=""
                                        @endif>
                                        <label class="custom-control-label" for="{{ $key }}" style="padding-top:3px;"><b>{{ ucwords($key) }} Module</b></label>
                                    </td>
                                    @foreach ($permission as $key2 => $item)
                                    <td>
                                        <input type="checkbox" name="permissions[]" class="custom-control-input childPermission" data-kunci="{{ $item->name }}" id="{{ $item->name }}" value="{{ $item->id }}" @if (in_array($item->id,$rolePermissions))
                                            checked=""
                                        @endif>
                                        <label class="custom-control-label" for="{{ $item->name }}" style="padding-top:3px;">{{ ucwords(explode('-', $item->name)[1]) }}</label>
                                    </td>
                                    @endforeach
                                </tr>
                            @endforeach                            
                        </table>                                                                                                                        
                    </div>
                </div>
                <div class="card-footer">                    
                    <a href="{{ route('roles.index') }}" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@section('jsAdded')
    <script>
        let kunci = null;
        let isChecked = null;
        let create = null;
        let list = null;
        let edit = null;
        let del = null;

        $(document).on('click','.parentPermission',function(){
            kunci = $(this).data('kunci');
            isChecked= $('#' + kunci).is(":checked");
            create = kunci+'-create';
            list = kunci+'-list';
            edit = kunci+'-edit';
            del = kunci+'-delete';
            if (isChecked == true) {
                $('#' + create).prop("checked", true );
                $('#' + list).prop("checked", true );
                $('#' + edit).prop("checked", true );
                $('#' + del).prop("checked", true );
            }else {
                $('#' + create).prop("checked", false );
                $('#' + list).prop("checked", false );
                $('#' + edit).prop("checked", false );
                $('#' + del).prop("checked", false );
            }
        });

        // let childKey = null;
        // let
        // $(document).on('click','.childPermission',function(){
        //     kunci = $(this).data('kunci');
        //     isChecked= $('#' + kunci).is(":checked");
        //     create = kunci+'-create';
        //     list = kunci+'-list';
        //     edit = kunci+'-edit';
        //     del = kunci+'-delete';
        //     if (isChecked == true) {
        //         $('#' + create).prop("checked", true );
        //         $('#' + list).prop("checked", true );
        //         $('#' + edit).prop("checked", true );
        //         $('#' + del).prop("checked", true );
        //     }else {
        //         $('#' + create).prop("checked", false );
        //         $('#' + list).prop("checked", false );
        //         $('#' + edit).prop("checked", false );
        //         $('#' + del).prop("checked", false );
        //     }
        // });

    </script>
@endsection
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Roles Page</title>
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Roles Management</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Roles</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th width="40">NO</th>
                    <th>ROLE NAME</th>                    
                    <th width="80">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($roles as $key => $role)
                        <tr>
                            <td class="text-center">{{$loop->iteration}}</td>
                            <td>{{ $role->name }}</td>                        
                            <td class="text-center">
                                @can('role-edit')
                                    <a href="/roles/{{$role->id}}/edit">
                                        <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-pencil"></i></button>
                                    </a>
                                @endcan
                                @can('role-delete')
                                    <button type="button" class="btn btn-danger btnDelete" data-nama="{{ $role->name }}" data-id="{{ $role->id }}" data-toggle="tooltip" data-placement="top" title="Delete">
                                        <i class="fa fa-trash"></i>
                                    </button>                            
                                @endcan
                            </td>
                        </tr>                        
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
    @include('includes.modals_delete')
    @include ('includes.script')
    @can('role-create')
        <script type="text/javascript">
            $(document).ready(function(){
                $("#data-admin_length").append('<a  href="{{ route('roles.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Add Role</button></a>');
            });
        </script>
    @endcan
    @section('jsAdded')
        <script>
            let id = null;
            let url = null;
            let msg = null;
            let name = null;

            $(document).on('click','.btnDelete',function(){
                id = $(this).data('id');
                name = $(this).data('nama');
                url = "{{ route('roles.destroy', '') }}"+"/"+id;
                msg = "Are you sure to delete this role ("+name+") ?";
                $('#formDelete').attr('action', url);            
                $('#modalContent').empty();
                $('#modalContent').append(msg);
                $('#modalDelete').show();
            });

            $(document).on('click','.btnCancel',function(){            
                $('#modalDelete').hide();
            });
        </script>
    @endsection
@endsection